### ISSUE TITLE
Certificate not trusted MQTT connections

### ISSUE THREAD

**Issue by ghost** [itsMoji/Instagram_SSL_Pinning#90] opened 2021-02-08 03:15 UTC
The libliger.so patch on the `verifyWithMetrics` function works fine with HTTP traffic, but there's likely a second unpatched certificate check for the MQTT connections.

I get the following error with mitmproxy configured as a SOCKS5 proxy: 
`Client handshake failed. The client may not trust the proxy's certificate for edge-mqtt.facebook.com.`

**Comment by enriquejr99** [comment] 2021-02-08 17:40
After enabling Facebook's [whitehat](https://www.facebook.com/whitehat) settings this handshake issue doesn't happen, which agrees with the theory of a second certificate check for these kind of connections. However, mitmproxy now throws a `Bad HTTP Request` error instead. This new error is likely because mitmproxy doesn't support MQTToT.

**Comment by enriquejr99** [comment] 2021-03-03 08:06
Actually, I just checked this with the latest Instagram version and I am able to read MQTT traffic even without a patched `libliger.so` file at all. It appears to me there is no SSL pinning mechanism in place for the `edge-mqtt.facebook.com` host.

Can anyone else reproduce this issue?

**Comment by Nerixyz** [comment] 2021-03-03 12:43
> Bad HTTP Request

MQTT isn't HTTP is you didn't know. I'd guess charles would work but I'm not sure. I'm fine with using frida.

**Comment by enriquejr99** [comment] 2021-03-03 20:37
If anyone gets the `Bad HTTP Request` error, use the `--raw-tcp` option with mitmdump so it doesn't try to parse the MQTT traffic as HTTP. I had to do this.

I'd suggest closing this issue as there is no SSL pinning for this host.

**Comment by enriquejr99** [comment] 2021-03-04 23:35
I'd like to point out that you don't need to install the proxy certificate on your device to intercept HTTP traffic as this certificate is pinned, but you will need to install it in order to intercept the MQTT traffic for the `edge-mqtt.facebook.com` host, as that certificate is not pinned and is therefore verified against Android's trusted certificate authorities.

Maybe author has not installed the proxy certificate or is using an outdated proxy certificate?

**Closed** 2021-03-06 13:22 UTC
